name: Test with Python 3.8

on:
  push:
  pull_request:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  extras:
    name: Test "Extras"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install httpx yt-dlp
    - name: Sync
      run: python tests/sync/extras.py
    - name: Async
      run: python tests/async/extras.py
  playlists:
    name: Test "Playlists"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install httpx
    - name: Sync
      run: python tests/sync/playlists.py
    - name: Async
      run: python tests/async/playlists.py
  search:
    name: Test "Search"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install httpx
    - name: Sync
      run: python tests/sync/search.py
    - name: Async
      run: python tests/async/search.py
